### PR TITLE
chore: Add the macOS runner to the matrix strategy

### PR DESCRIPTION
**Pull request by realtimetodie**
Adds the macOS runner to the matrix strategy of the test workflow job.

### CODE REVIEW

**Comment by realtimetodie** [comment]
Related

- https://github.com/aspect-build/rules_js/pull/828
- https://github.com/aspect-build/rules_esbuild/pull/118
- https://github.com/aspect-build/rules_terser/pull/64
- https://github.com/aspect-build/rules_webpack/pull/89
- https://github.com/aspect-build/rules_rollup/pull/65
- https://github.com/aspect-build/rules_jest/pull/94
- https://github.com/aspect-build/rules_jasmine/pull/35
- https://github.com/aspect-build/rules_cypress/pull/27
- https://github.com/aspect-build/rules_deno/pull/15

**Comment by realtimetodie** [comment]
Tested and verified in a private repository.

**Comment by gregmagolan** [comment]
Sweet. Thanks for the added coverage 🙏

**Review by gregmagolan — APPROVED** [review]

**Comment by alexeagle** [comment]
I just reverted this in https://github.com/aspect-build/rules_ts/commit/36be3ddce2e87963935eb9e134b1cc331623af8c because it blew up our February GH Actions budget for the whole aspect-build org, oops

**Pull request merged**
