### PR TITLE
@aws-sdk packages fail to compile

### PR DESCRIPTION
**Pull request by jfirebaugh**
(Bug report in the form of a PR with a failing example. Feel free not to merge this PR.)

`@aws-sdk` packages fail with TS2307 errors when used as deps in `ts_project` targets. For example:

```
$ bazel build //examples/aws-sdk:ts                                       
INFO: Analyzed target //examples/aws-sdk:ts (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/john/figma/rules_ts/examples/aws-sdk/BUILD.bazel:3:11: Compiling TypeScript project //examples/aws-sdk:ts [tsc -p examples/aws-sdk/tsconfig.json] failed: (Exit 1): tsc_worker.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh @bazel-out/darwin_arm64-fastbuild/bin/examples/aws-sdk/index.js-0.params

examples/node_modules/.aspect_rules_js/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseDualstackEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
examples/node_modules/.aspect_rules_js/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseFipsEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
examples/node_modules/.aspect_rules_js/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/regionConfig/config.d.ts(1,59): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
examples/node_modules/.aspect_rules_js/@aws-sdk+middleware-bucket-endpoint@3.127.0/node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeDisableMultiregionAccessPointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
examples/node_modules/.aspect_rules_js/@aws-sdk+middleware-bucket-endpoint@3.127.0/node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeUseArnRegionConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
examples/node_modules/.aspect_rules_js/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-types/configurations.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

Target //examples/aws-sdk:ts failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.289s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

The same project builds successfully with `pnpm i && ./node_modules/.bin/tsc --project aws-sdk/tsconfig.json`.

### CODE REVIEW

**Comment by gregmagolan** [comment]
This seems to be a phantom/undeclared dependency issue. pnpm outside of bazel will hoist one version of every package to `node_modules/.pnpm/node_modules` which allows for packages in the virtual store to depend on packages that they don't declare as dependencies in their package.json. rules_js can't work the same way without breaking lazy fetching and lazy linking but you can inject missing dependencies via `pnpm.packageExtensions`:

```
$ git diff examples/package.json
diff --git a/examples/package.json b/examples/package.json
index dadc122..f1ba43e 100644
--- a/examples/package.json
+++ b/examples/package.json
@@ -8,5 +8,36 @@
         "@types/node": "18.6.1",
         "date-fns": "2.29.1",
         "typescript": "4.7.4"
+    },
+    "pnpm": {
+        "packageExtensions": {
+            "@aws-sdk/config-resolver": {
+                "peerDependencies": {
+                    "@aws-sdk/node-config-provider": "*"
+                }
+            },
+            "@aws-sdk/middleware-bucket-endpoint": {
+                "peerDependencies": {
+                    "@aws-sdk/node-config-provider": "*"
+                }
+            },
+            "@aws-sdk/middleware-retry": {
+                "peerDependencies": {
+                    "@aws-sdk/node-config-provider": "*"
+                }
+            },
+            "@aws-sdk/client-s3": {
+                "peerDependencies": {
+                    "@aws-sdk/config-resolver": "*",
+                    "@aws-sdk/middleware-bucket-endpoint": "*",
+                    "@aws-sdk/middleware-retry": "*"
+                }
+            },
+            "@aws-sdk/shared-ini-file-loader": {
+                "peerDependencies": {
+                    "@aws-sdk/types": "*"
+                }
+            }
+        }
     }
 }
```

The above change to `examples/package.json` followed by a `pnpm i --lockfile-only` in `examples` and the build should pass.

**Comment by gregmagolan** [comment]
The issue can be reproduced outside of bazel by deleting the `node_modules/.pnpm/node_modules` folder after install

```
$ pnpm i
$ rm -rf node_modules/.pnpm/node_modules
$ ./node_modules/.bin/tsc --project aws-sdk/tsconfig.json
node_modules/.pnpm/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseDualstackEndpointConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseFipsEndpointConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+config-resolver@3.130.0/node_modules/@aws-sdk/config-resolver/dist-types/regionConfig/config.d.ts:1:59 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors, LocalConfigOptions } from "@aws-sdk/node-config-provider";
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+middleware-bucket-endpoint@3.127.0/node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeDisableMultiregionAccessPointConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+middleware-bucket-endpoint@3.127.0/node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeUseArnRegionConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-types/configurations.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 6 errors in 6 files.

```

**Comment by gregmagolan** [comment]
You can also reproduce by changing the pnpm hoist settings by dropping an `.npmrc` next to the `package.json` file before running `pnpm i`:

`examples/.npmrc`
```
hoist=false
```

This turns off hoisting which is on by default with pnpm https://pnpm.io/npmrc#hoist

**Comment by cgrindel** [comment]
There has not been much activity on this PR, recently. I will close it for now @jfirebaugh If you believe that this is still an issue, please feel free to reopen the PR.

**Pull request closed without merging**
