### PR TITLE
Failing e2e test with an npm dep

### PR DESCRIPTION
**Pull request by jfirebaugh**
This is a bug report in the form of a pull request containing a failing e2e test. The test is reduced from my own attempt to use `ts_project` with deps consisting of packages obtained via `translate_pnpm_lock`, `npm_repositories`, and `link_js_packages`. This test fails with the following error:

```
$ bazel build :ts 
INFO: Analyzed target //:ts (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/john/figma/rules_ts/e2e/deps/BUILD:7:11: Compiling TypeScript project //:ts [tsc -p tsconfig.json] failed: (Exit 2): _tsc_launcher.sh failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/npm_typescript/_tsc_launcher.sh --project tsconfig.json --outDir . --rootDir .

Use --sandbox_debug to see verbose messages from the sandbox
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions
Target //:ts failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.542s, Critical Path: 1.31s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Building with `--sandbox_debug` and examining the sandbox, the `node_modules` directory exists, but is empty.

### CODE REVIEW

**Comment by alexeagle** [comment]
Thanks for the convenient repro. I don't think there's a mistake in your code.

```
alexeagle@13-Aspect-MBP deps % ls -R bazel-bin
_validate_ts_options.optionsvalid.d.ts	foo.ts					tsconfig.json
foo.js					node_modules

bazel-bin/node_modules:
@types

bazel-bin/node_modules/@types:
node
alexeagle@13-Aspect-MBP deps % ls bazel-bin/node_modules/@types/node
LICENSE				dns				module.d.ts			string_decoder.d.ts
```

IIRC, the `typescript` module starts searching for node_modules relative to the location of `tsc.js` rather than from the working directory. `tsc.js` is in `$(bazel info output_base)/external/npm_typescript/package/lib`.

**Comment by jfirebaugh** [comment]
My conclusion after familiarizing myself with the internals is that `link_js_package_direct` needs to construct a `DeclarationInfo` that points to the symlink it creates, rather than simply [forwarding `ctx.attr.src[DeclarationInfo]`](https://github.com/aspect-build/rules_js/blob/f80b58ca19a67d5676031920d053e43f1b1948e9/js/private/link_js_package.bzl#L260).

The chain of dependencies is as follows:

`@npm//@types/node` 
-> is an alias for `@//:jsp__at_types_node` 
-> is an alias for `@//:jsp__at_types_node__17.0.33` 
-> is a `link_js_package_direct` with `src = //:jsp__at_types_node__17.0.33__store`
-> is a `link_js_package_store` with `deps = jsp__at_types_node__17.0.33__pkg`
-> is a `link_js_package_store` with `src = @npm__at_types_node__17.0.33//:jsp_source_directory`
-> is a `js_package`

The inputs for the `TsProject` action include `bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@17.0.33/node_modules/@types/node`:

```
$ bazel aquery 'mnemonic("TsProject", :ts)' 
INFO: Analyzed target //:ts (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
action 'Compiling TypeScript project //:ts [tsc -p tsconfig.json]'
  Mnemonic: TsProject
  Target: //:ts
  Configuration: darwin-fastbuild
  Execution platform: @local_config_platform//:host
  ActionKey: c900bc28d701490b51c2a35f7b80969d16f3324d7c2aeb54e2ba33f9c0792458
  Inputs: [bazel-out/darwin-fastbuild/bin/_validate_ts_options.optionsvalid.d.ts, bazel-out/darwin-fastbuild/bin/foo.ts, bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@17.0.33/node_modules/@types/node, bazel-out/darwin-fastbuild/bin/tsconfig.json, bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/npm_typescript/_tsc_launcher.sh, bazel-out/darwin-opt-exec-2B5CBBC6/internal/_middlemen/external_Snpm_Utypescript_S_Utsc_Ulauncher.sh-runfiles]
  Outputs: [bazel-out/darwin-fastbuild/bin/foo.js]
  Environment: [BAZEL_BINDIR=bazel-out/darwin-fastbuild/bin]
  Command Line: (exec bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/npm_typescript/_tsc_launcher.sh \
    --project \
    tsconfig.json \
    --outDir \
    . \
    --rootDir \
    .)
```


This input ultimately comes from the `DeclarationInfo` for `@//:jsp__at_types_node__17.0.33__store`, constructed here:

https://github.com/aspect-build/rules_js/blob/f80b58ca19a67d5676031920d053e43f1b1948e9/js/private/link_js_package.bzl#L217-L220

Where `direct_files` is sourced from the `else` branch:

https://github.com/aspect-build/rules_js/blob/f80b58ca19a67d5676031920d053e43f1b1948e9/js/private/link_js_package.bzl#L158-L204

Producing the following provider:

```
@rules_nodejs//nodejs/private/providers:declaration_info.bzl%DeclarationInfo = struct(
    declarations = depset([
        <generated file node_modules/.aspect_rules_js/@types+node@17.0.33/node_modules/@types/node>,
    ]),
    transitive_declarations = depset([
        <generated file node_modules/.aspect_rules_js/@types+node@17.0.33/node_modules/@types/node>,
    ]),
    type_blocklisted_declarations = depset([]),
),
```

Which is then consumed by `ts_project`:

https://github.com/aspect-build/rules_ts/blob/a866c0e9e577ad3ac27961526a4f7df4ec6330e5/ts/private/ts_project.bzl#L90-L91

But tsc is never going to search this `.aspect_rules_js` subdirectory of `node_modules` for type declarations. Instead the `TsProject` inputs needs to include `bazel-out/darwin-fastbuild/bin/node_modules/@types/node`, the symlink that `link_js_package_direct` creates.

**Comment by alexeagle** [comment]
ooh nice debugging @jfirebaugh, thanks - I'll try to close the loop on it first thing tomorrow

**Comment by alexeagle** [comment]
I think this e2e should work now rebased to HEAD.

**Pull request closed without merging**
