### PR TITLE
chore: update to latest stardoc

### PR DESCRIPTION
**Pull request by gregmagolan**
Pre-factor from https://github.com/aspect-build/rules_ts/pull/593

Bit of tidying and sorting of the deps as well

### CODE REVIEW

**Review by kormide — APPROVED** [review]

**Review by jbedard — COMMENTED** [review]
Shouldn't the `http_archive` and some `load("@io_bazel_stardoc//...)` calls be the only stuff in this PR?

**Comment by gregmagolan** [comment]
> Shouldn't the `http_archive` and some `load("@io_bazel_stardoc//...)` calls be the only stuff in this PR?

I added some deps cleanup and sorting to make it more interesting for reviewers :wink:

**Comment by gregmagolan** [comment]
Looks like I also need to bump the min bazel-lib here to 1.40.2 to pick up this fix to the stardoc_with_diff_test docs rule used in this repo.

```
commit 27e3b10472e4cdd36fff23b5f8fcf0101dacfd6a (tag: v1.40.2, tag: v1.40.1)
Author: Greg Magolan <gmagolan@gmail.com>

    fix: merge user tags in stardoc_with_diff_test (#746)
```

**Comment by jbedard** [comment]
> I added some deps cleanup and sorting to make it more interesting for reviewers 😉

More confusing is not "interesting" 😅

**Pull request merged**
