### PR TITLE
e2e test with a .d.ts dep

### PR DESCRIPTION
**Pull request by jfirebaugh**
This is an e2e test that replicates a pattern we have been using with @bazel/typescript that does not work with rules_ts.

* Directory `a` `exports_files` `a.d.ts`, a TypeScript declaration file
* Directory `b` includes `a.d.ts` in a `ts_project`'s `srcs` and imports it with an editor-friendly relative path (`'../a/a'`)

This produces the following error:

```
$ bazel build //b:ts
Starting local Bazel server and connecting to it...
ERROR: /Users/john/figma/rules_ts/e2e/d.ts_dep/b/BUILD:3:11: in _ts_project rule //b:ts: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_rules_ts/ts/private/ts_project.bzl", line 156, column 47, in _ts_project_impl
		inputs = copy_files_to_bin_actions(ctx, inputs),
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_bazel_lib/lib/private/copy_to_bin.bzl", line 59, column 36, in copy_files_to_bin_actions
		return [copy_file_to_bin_action(ctx, file, is_windows = is_windows) for file in files]
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_bazel_lib/lib/private/copy_to_bin.bzl", line 38, column 35, in copy_file_to_bin_action
		dst = ctx.actions.declare_file(file.basename, sibling = file)
Error in declare_file: the output artifact 'a/a.d.ts' is not under package directory 'b' for target '//b:ts'
ERROR: /Users/john/figma/rules_ts/e2e/d.ts_dep/b/BUILD:3:11: Analysis of target '//b:ts' failed
ERROR: Analysis of target '//b:ts' failed; build aborted: 
INFO: Elapsed time: 9.118s
INFO: 0 processes.
```

Is this pattern intended to work with rules_js/ts? If not, what's the recommended replacement?

(This may affect regular `.ts` files as well as `.d.ts`. I'm not sure. `.d.ts` was where I encountered it; we're not yet building anything with Bazel that relies on relative imports of `.ts` files outside the package.)

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Here's a very similar issue (same "Error in declare_file ... not under package directory") with rules_js: https://github.com/aspect-build/rules_js/compare/main...figma:jfirebaugh/e2e-mocha

```
$ bazel build //b:ts
ERROR: /Users/john/figma/rules_ts/e2e/d.ts_dep/b/BUILD:3:11: in _ts_project rule //b:ts: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_rules_ts/ts/private/ts_project.bzl", line 156, column 47, in _ts_project_impl
		inputs = copy_files_to_bin_actions(ctx, inputs),
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_bazel_lib/lib/private/copy_to_bin.bzl", line 59, column 36, in copy_files_to_bin_actions
		return [copy_file_to_bin_action(ctx, file, is_windows = is_windows) for file in files]
	File "/private/var/tmp/_bazel_johnfirebaugh/569c03f4f0f6841bd5e96cbaf2febff3/external/aspect_bazel_lib/lib/private/copy_to_bin.bzl", line 38, column 35, in copy_file_to_bin_action
		dst = ctx.actions.declare_file(file.basename, sibling = file)
Error in declare_file: the output artifact 'a/a.d.ts' is not under package directory 'b' for target '//b:ts'
ERROR: /Users/john/figma/rules_ts/e2e/d.ts_dep/b/BUILD:3:11: Analysis of target '//b:ts' failed
ERROR: Analysis of target '//b:ts' failed; build aborted: 
INFO: Elapsed time: 0.271s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 3 targets configured)
```

I'm assuming this is so similar that it's not worth opening a separate issue, but let me know if you'd like me to do that.

**Comment by alexeagle** [comment]
There's no need for these to be e2e tests, which are slower and just detect defects related to relative/absolute workspace references.

See https://github.com/aspect-build/rules_ts/pull/21 where I've taken one of your commits and moved the load-bearing bits into the examples/ folder - can you send red PRs in that shape instead? Thanks!

**Comment by alexeagle** [comment]
So this error is mostly because any sources passed to a rules_js-based rule need to be copied to the output folder, and yours is in a different package, so the copy needs to go there.

change a/BUILD to
```
load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")

copy_to_bin(
    name = "a",
    srcs = ["a.d.ts"],
    visibility = ["//:__subpackages__"]
)
```

Then there's also a minor bug with rootpath calculation which I'll send a PR for

**Comment by alexeagle** [comment]
Added a fix for the remaining bug to the already-open https://github.com/aspect-build/rules_ts/pull/21/files - could you sign CLA there so I can merge?

**Comment by alexeagle** [comment]
I think this e2e should work now rebased to HEAD. (and with the copy_to_bin fix noted above)

**Pull request closed without merging**
