### PR TITLE
Updated typescript versions

### PR DESCRIPTION
**Pull request by UebelAndre**
**Type of change**

- [x] Chore (any other change that doesn't affect source or test files)

**Test plan**

- [x] Covered by existing test cases

### CODE REVIEW

**Review by gregmagolan — APPROVED** [review]

**Comment by gregmagolan** [comment]
cc @thesayyn for test-worker CI failures

**Comment by thesayyn** [comment]
> cc @thesayyn for test-worker CI failures

i have 1.0 coming up for rules_oci. so i won't be able to take a look this week.

**Comment by alexeagle** [comment]
To unblock this, I'm just going to fix up the worker test to still test against the current version rather than 5.0.

**Review by gregmagolan — APPROVED** [review]
🌮

**Pull request merged**
