### PR TITLE
Fix transitive propagation of npm deps

### PR DESCRIPTION
**Pull request by mvukov**
Fixes:
* https://github.com/aspect-build/rules_ts/issues/268
* https://github.com/aspect-build/rules_jest/issues/72

### CODE REVIEW

**Comment by mvukov** [comment]
@alexeagle @thesayyn PTAL.

**Comment by gregmagolan** [comment]
Adding this my list of OSS bug squashing for later this week

**Comment by alexeagle** [comment]
We just need to be careful we don't re-introduce eager type-checking or cascading rebuilds.

**Comment by gregmagolan** [comment]
I'll keep it in mind. We did add analysis test cases to cover that now.

**Comment by mvukov** [comment]
Anything I can help with?

**Comment by gregmagolan** [comment]
Thanks for the ping. I didn't have time to get to this before the Christmas break. Will look soon. This needs a bit of time to understand the side-effects of this change. In the meantime, it's a small patch to carry locally if you need this change.

**Comment by flolu** [comment]
@gregmagolan awesome, thanks! How would I apply this patch to `ts_project.bzl` and use it for my project in the meantime?

**Comment by gregmagolan** [comment]
It's a very common practice to patch Bazel rules with `http_archive` in your WORKSPACE. Even rule sets sometimes patch other rule sets. For example, https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl#L78

**Comment by mvukov** [comment]
@gregmagolan Friendly ping :) PTAL when you find some time.

**Comment by gregmagolan** [comment]
Turns out that @jbedard and I have been discussing the underlying issue that the PR address already. I go into the details of the problem in this comment https://github.com/aspect-build/rules_ts/issues/268#issuecomment-1401598145. The principled fix for this starts with a PR in rules_js to introduce a `dev_npm_deps` attribute. Closing this PR as the fix will take a different shape once the change in rules_js lands. Will leave https://github.com/aspect-build/rules_ts/issues/268 open.

**Pull request closed without merging**
