### PR TITLE
test: add case for filegroup of srcs

### PR DESCRIPTION
**Pull request by alexeagle**
Part of #23

### CODE REVIEW

**Comment by jbedard** [comment]
How about generated files? A `genrule` that just copies the ts files?

**Comment by alexeagle** [comment]
We have that in `examples/simple` already. I'll move it over here since generated code isn't the simple case.

**Comment by jbedard** [comment]
In this PR or another?

**Review by jbedard — APPROVED** [review]

**Comment by alexeagle** [comment]
moved it here, PTAL

**Review by jbedard — APPROVED** [review]
👍

**Pull request merged**
