### PR TITLE
fix: prefix host call

### PR DESCRIPTION
**Pull request by thesayyn**

### CODE REVIEW

**Review by jbedard — APPROVED** [review]

**Comment by jbedard** [comment]
Was this crashing?

**Comment by thesayyn** [comment]
> Was this crashing?

unfortunately, yes. and it went unnoticed. I guess it's time for #114

**Comment by jbedard** [comment]
> unfortunately, yes. and it went unnoticed. I guess it's time for https://github.com/aspect-build/rules_ts/issues/114

I think we can even write plain js but still typecheck it by putting types in comments and just type inference on its own is useful.

**Comment by thesayyn** [comment]
> > unfortunately, yes. and it went unnoticed. I guess it's time for #114
> 
> I think we can even write plain js but still typecheck it by putting types in comments and just type inference on its own is useful.

i agree.

**Pull request merged**
